### PR TITLE
Fix a mismanagement of the hash table that could lead to data loss.

### LINKED ISSUE #1924: Crash in objc_loadWeakRetained
We’re seeing crashes with the following top of the stack trace:

```
libobjc2!objc_msgSend+0x47:

Stack trace:
ChildEBP RetAddr  
0888ef34 5528d5b5 libobjc2!objc_msgSend+0x47 [c:\users\duhowett\src\winobjc\deps\3rdparty\libobjc2\msvc\objc_msgsend.x86-32.masm.inl @ 15732480]
0888ef5c 007110f4 libobjc2!objc_loadWeakRetained+0xc5 [c:\users\duhowett\src\winobjc\deps\3rdparty\libobjc2\arc.m @ 712]
```

The failure reasons are `NULL_CLASS_PTR_READ_c0000005_libobjc2.dll!objc_loadWeakRetained`
and `NULL_POINTER_READ_c0000005_libobjc2.dll!objc_loadWeakRetained`.

The crash is in [deps\3rdparty\libobjc2\arc.m:712](https://github.com/Microsoft/libobjc2/blob/58a7fd2146eaa7312bd315e9e74e45433198e91f/arc.m#L712) and it looks like _objc_weak_load/_NSWeakLoad() is getting an invalid reference to the object, which causes the crash in objc_msgSend().

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
```
This commit fixes a data loss bug in the hopscotch hash table
implementation. Removing values from the table can result in other
values becoming disconnected and lost.

Let A, B, and C be values that all hash to slot 0.
Assume the hopscotch distance factor H = 2.

   0     1     2
+-----+-----+-----+
|     |     |     |
+-----+-----+-----+

After adding A
   0     1     2
+-----+-----+-----+
|  A  |     |     |
+-----+-----+-----+
   Neighbors =

After adding B
   0     1     2
+-----+-----+-----+
|  A  |  B  |     |
+-----+-----+-----+
   Neighbors = 1

After adding C
   0     1     2
+-----+-----+-----+
|  A  |  B  |  C  |
+-----+-----+-----+
   Neighbors = 1, 2

If we then remove B,
   0     1     2
+-----+-----+-----+
|  A  | [X] |  C  |
+-----+-----+-----+
   Neighbors = 1, 2

* It is replaced with a placeholder [X].
* A's neighbor table is not updated to reflect the loss.

If we then remove A,
   0     1     2
+-----+-----+-----+
| [X] |  C  | [X] |
+-----+-----+-----+
   Neighbors = 1

* The table is rebalanced to promote A's lowest neighbor to the primary
  cell position.
* C from cell 2 is promoted to cell 1, and remains cell 0's
  neighbor.

The bug manifests if [X] the placeholder value passes the null check set
out in MAP_TABLE_VALUE_NULL; that is, the placeholder is "effectively
null".

Looking up the key that matches C will first evaluate its base cell, the
one that collided with the key in the first place. Since that is
placeholder [X], and [X] is "effectively null", the lookup stops.

C is never retrieved from the hash table.

---
The expedient solution to this bug is to update cell 0's neighbors when
B is first removed, effectively skipping the hole:

If we then remove B,
   0     1     2
+-----+-----+-----+
|  A  | [X] |  C  |
+-----+-----+-----+
   Neighbors = 2 <<< HERE

Therefore, the promotion that happens when A is later removed places C
in cell 0.

   0     1     2
+-----+-----+-----+
|  C  | [X] | [X] |
+-----+-----+-----+
   Neighbors =
```

Fixes Microsoft/WinObjC#1924.

### CODE REVIEW

File: hash_table.h [hunk 1]
```diff
@@ -392,6 +392,20 @@ static void PREFIX(_remove)(PREFIX(_table) *table, void *key)
 	MAP_LOCK();
 	PREFIX(_table_cell) cell = PREFIX(_table_get_cell)(table, key);
 	if (NULL == cell) { return; }
+
+	uint32_t hash = MAP_TABLE_HASH_KEY(key);
+	PREFIX(_table_cell) baseCell = PREFIX(_table_lookup)(table, hash);
+	if (baseCell && baseCell <= cell && cell - baseCell <= 32) {
+		uint32_t jump = 1 << (cell - baseCell - 1);
+		if ((baseCell->secondMaps & jump)) {
```
Comment (aballway) [inline hash_table.h:400]: nit: no need to check this here since we want the jump bit to be 0 either way

**Review by aballway — APPROVED** [review]

**Review by MSFTFox — APPROVED** [review]

**Review by bbowman — APPROVED** [review]

File: hash_table.h [hunk 2]
```diff
@@ -392,6 +392,20 @@ static void PREFIX(_remove)(PREFIX(_table) *table, void *key)
 	MAP_LOCK();
 	PREFIX(_table_cell) cell = PREFIX(_table_get_cell)(table, key);
 	if (NULL == cell) { return; }
+
+	uint32_t hash = MAP_TABLE_HASH_KEY(key);
+	PREFIX(_table_cell) baseCell = PREFIX(_table_lookup)(table, hash);
+	if (baseCell && baseCell <= cell && cell - baseCell <= 32) {
```
Comment (rajsesh) [inline hash_table.h:398]: Is the implication here that there can be only 32 collisions? Some comments here would help.

**Review by rajsesh — APPROVED** [review]

File: hash_table.h [hunk 3]
```diff
@@ -392,6 +392,20 @@ static void PREFIX(_remove)(PREFIX(_table) *table, void *key)
 	MAP_LOCK();
 	PREFIX(_table_cell) cell = PREFIX(_table_get_cell)(table, key);
 	if (NULL == cell) { return; }
+
+	uint32_t hash = MAP_TABLE_HASH_KEY(key);
```
Comment (ms-jihua) [inline hash_table.h:396]: do we have a rough idea of the perf hit of this change?

Comment (DHowett-MSFT) [reply hash_table.h:396]: @ms-jihua roughly: negligible. The hash function in use here takes a 32-bit value and shifts it around to return another 32-bit value, and `table_get_cell` is practically just `return &table[hash%size]`.

**Review by ms-jihua — APPROVED** [review]
